"""
app.py
------
Streamlit AI Dashboard — Retail Inventory Decision Engine
Layer 1: Executive Summary (auto-generated on load)
"""

import streamlit as st
from datetime import date
from data_context import load_data, build_ai_context
from groq_client import ask_groq, ask_groq_with_history

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Retail Inventory AI",
    page_icon="🏪",
    layout="wide",
)

# ── Load data (cached so it only runs once per session) ────────────────────────
@st.cache_data
def get_data():
    return load_data()

@st.cache_data
def get_context(_df):
    return build_ai_context(_df)

df = get_data()
ai_context = get_context(df)

# ── Header ─────────────────────────────────────────────────────────────────────
st.title("🏪 Retail Inventory Decision Engine")
st.caption(
    "AI-powered stock risk analysis · 10 stores · 100 SKUs · "
    "Powered by Llama 3.3 via Groq"
)
st.divider()

# ── Layer 1: Metric Cards ──────────────────────────────────────────────────────
st.subheader("📊 Inventory Snapshot")

critical_count = int((df["priority_level"] == "CRITICAL").sum())
high_count     = int((df["priority_level"] == "HIGH").sum())
needs_action   = int(df["needs_action"].sum())
most_at_risk   = (
    df[df["priority_level"] == "CRITICAL"]
    .groupby("store_id")
    .size()
    .idxmax()
)

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        label="🔴 CRITICAL SKUs",
        value=critical_count,
        help="Top 10% priority score — immediate restock required",
    )

with col2:
    st.metric(
        label="🟠 HIGH SKUs",
        value=high_count,
        help="Next 20% priority score — monitor closely",
    )

with col3:
    st.metric(
        label="⚡ SKUs Needing Action",
        value=needs_action,
        help="All SKUs where recommended_action is not NO_ACTION",
    )

with col4:
    st.metric(
        label="🏪 Most At-Risk Store",
        value=f"Store {most_at_risk}",
        help="Store with the highest number of CRITICAL SKUs",
    )

st.divider()

# ── Store Risk Chart ───────────────────────────────────────────────────────────
st.subheader("🏪 Store Risk Overview")
st.caption("CRITICAL SKUs per store — sorted by highest risk")

store_critical = (
    df[df["priority_level"] == "CRITICAL"]
    .groupby("store_id")
    .size()
    .sort_values(ascending=True)
    .reset_index()
)
store_critical.columns = ["store_id", "critical_count"]
store_critical["store_label"] = "Store " + store_critical["store_id"].astype(str)

def get_bar_color(count):
    if count >= 13:
        return "#E24B4A"
    elif count >= 9:
        return "#EF9F27"
    else:
        return "#888780"

import plotly.graph_objects as go

colors = [get_bar_color(c) for c in store_critical["critical_count"]]

fig = go.Figure(go.Bar(
    x=store_critical["critical_count"],
    y=store_critical["store_label"],
    orientation="h",
    marker_color=colors,
    text=store_critical["critical_count"],
    textposition="outside",
))

fig.update_layout(
    height=350,
    margin=dict(l=0, r=40, t=10, b=30),
    xaxis=dict(
        title="Number of critical SKUs",
        showgrid=True,
        gridcolor="rgba(128,128,128,0.15)",
    ),
    yaxis=dict(showgrid=False),
    plot_bgcolor="rgba(0,0,0,0)",
    paper_bgcolor="rgba(0,0,0,0)",
    font=dict(color="#888780", size=12),
)

st.plotly_chart(fig, use_container_width=True)

# ── Layer 1: AI Executive Summary ──────────────────────────────────────────────
st.subheader("🤖 AI Executive Summary")
st.caption("Auto-generated by Llama 3.3 · Based on live inventory data")

# We use st.cache_data so the AI summary is generated once per session,
# not on every rerun (saves tokens + speeds up the app).
@st.cache_data
def generate_executive_summary(context: str) -> str:
    system_prompt = f"""You are a senior supply chain analyst presenting to C-suite executives.
You have access to the following real inventory data:

{context}

Your job: write a concise, professional executive summary (3–4 short paragraphs).
Cover:
1. Overall inventory health and risk level
2. Which stores and product categories need immediate attention
3. Key recommended actions for the operations team
4. One forward-looking observation

Rules:
- Be direct and business-focused. No fluff.
- Use specific numbers from the data.
- Do NOT use bullet points — write in flowing paragraphs.
- Maximum 200 words total.
"""
    return ask_groq(
        system_prompt=system_prompt,
        user_message="Generate the executive summary now.",
        temperature=0.4,
    )

with st.spinner("Generating AI executive summary..."):
    summary = generate_executive_summary(ai_context)

st.info(summary)

st.divider()

# ── Layer 2: Natural Language Q&A ─────────────────────────────────────────────
st.subheader("💬 Ask the AI Analyst")
st.caption("Ask anything about your inventory — grounded on real data")

# Initialize chat history in session state (persists across reruns)
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display existing chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Chat input box (appears at bottom of page)
if prompt := st.chat_input("e.g. Which stores have the most critical SKUs?"):

    # 1. Show user message immediately
    with st.chat_message("user"):
        st.markdown(prompt)

    # 2. Add to history
    st.session_state.messages.append({"role": "user", "content": prompt})

    # 3. Build system prompt with data context
    system_prompt = f"""You are a senior inventory analyst assistant.
You have access to the following real inventory data:

{ai_context}

Answer the user's question clearly and concisely.
Use specific numbers and store/product IDs from the data when relevant.
If the question is not related to inventory, politely redirect.
"""

    # 4. Get AI response
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            response = ask_groq_with_history(
                system_prompt=system_prompt,
                conversation_history=st.session_state.messages,
            )
        st.markdown(response)

    # 5. Add AI response to history
    st.session_state.messages.append({"role": "assistant", "content": response})

st.divider()

# ── Layer 3: Reorder Briefing Generator ───────────────────────────────────────
# ── Layer 3: Reorder Briefing Generator ───────────────────────────────────────
st.subheader("📋 Reorder Briefing Generator")
st.caption("One-click AI-generated procurement brief — ready to share with your operations team")

# Filter selector
priority_filter = st.radio(
    "Include which priority levels?",
    options=["CRITICAL only", "CRITICAL + HIGH"],
    horizontal=True,
)

# Generate button
if st.button("🚀 Generate Reorder Brief", type="primary"):

    # Filter data based on selection
    if priority_filter == "CRITICAL only":
        filtered_df = df[df["priority_level"] == "CRITICAL"]
    else:
        filtered_df = df[df["priority_level"].isin(["CRITICAL", "HIGH"])]

   # Round days to 1 decimal — cleaner for business documents
    filtered_df = filtered_df.copy()
    filtered_df["days_of_stock_remaining"] = filtered_df["days_of_stock_remaining"].round(1)

    urgent = filtered_df[filtered_df["days_of_stock_remaining"] <= 8].sort_values("days_of_stock_remaining")
    soon = filtered_df[filtered_df["days_of_stock_remaining"] > 8].sort_values("days_of_stock_remaining")

    # Format urgent items — consistent with Section 2 style
    urgent_formatted = ""
    for _, row in urgent.iterrows():
        urgent_formatted += f"  Store {row['store_id']} — Product {row['product_id']} ({row['category']}) — {row['days_of_stock_remaining']} days\n"

    # Build Section 2 grouped by store — one line per item, not one line per store
    soon_grouped = ""
    for store_id, group in soon.groupby("store_id"):
        soon_grouped += f"\nStore {store_id} ({len(group)} items):\n"
        for _, row in group.iterrows():
            soon_grouped += f"  - Product {row['product_id']} ({row['category']}) — {row['days_of_stock_remaining']} days\n"

    data_for_brief = f"""
ACT WITHIN 24-48 HOURS — items with 8 or fewer days of stock ({len(urgent)} total):
{urgent[['store_id','product_id','category','days_of_stock_remaining']].to_string(index=False)}

ACT WITHIN 1 WEEK — items with more than 8 days of stock ({len(soon)} total):
{soon_grouped}
"""

    system_prompt = f"""You are a supply chain operations assistant.
Today's date is {date.today().strftime("%B %d, %Y")}.

Generate a professional reorder brief. Sections 1 and 2 are already formatted — 
copy them EXACTLY as provided, character by character, no changes whatsoever.

REORDER BRIEF — {date.today().strftime("%B %d, %Y")}
Generated by Retail Inventory AI
{'='*50}

SUMMARY:
[Write 1 sentence: total SKUs needing action and which stores are highest risk]

{'='*50}
SECTION 1 — URGENT RESTOCK (act within 24-48 hours)
{urgent_formatted}

{'='*50}
SECTION 2 — RESTOCK WITHIN 1 WEEK
{soon_grouped}
{'='*50}
SECTION 3 — RECOMMENDED NEXT STEPS
[Write exactly 3 specific action items referencing actual store numbers and category names from the data]

Rules:
- Copy Section 1 and Section 2 EXACTLY as shown above — do not reformat, do not add commentary
- Only write the SUMMARY and SECTION 3 yourself
- No extra text outside the structure above
"""

    with st.spinner("Generating reorder brief..."):
        brief = ask_groq(
            system_prompt=system_prompt,
            user_message="Generate the reorder brief now.",
            temperature=0.2,
        )

    # Display the brief with built-in copy button
    st.code(brief, language=None)
    st.caption("💡 Click the copy icon on the top-right of the box above to copy the brief.")